=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/multisell.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="npcs" type="intList" minOccurs="0"/>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredient" type="Ingredient" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="production" type="Product" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="apply-taxes" type="xs:boolean" default="false"/>
            <xs:attribute name="gm-only" type="xs:boolean" default="false"/>
            <xs:attribute name="chance-based" type="xs:boolean" default="false"/>
            <xs:attribute name="maintain-enchantment" type="xs:boolean" default="false"/>
            <xs:attribute name="ingredient-multiplier" type="xs:double" default="1"/>
            <xs:attribute name="product-multiplier" type="xs:double" default="1"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Ingredient">
        <xs:complexContent>
            <xs:extension base="EnchantedItem">
                <xs:attribute name="consume" type="xs:boolean" default="true"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Product">
        <xs:complexContent>
            <xs:extension base="EnchantedItem">
                <xs:attribute name="chance" type="xs:double" default="0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/3429201.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd">
    <npcs>
        34292 <!-- Chef Monkey -->
    </npcs>
    <item>
        <ingredient id="70304" count="50"/> <!-- Tuna Fish -->
        <production id="90045"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>

    <!-- evo -->
    <item>
        <ingredient id="70304" count="100"/> <!-- Tuna Fish -->
        <production id="91031"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>
    <item>
        <ingredient id="70304" count="100"/> <!-- Tuna Fish -->
        <production id="91032"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>
    <item>
        <ingredient id="70304" count="100"/> <!-- Tuna Fish -->
        <production id="91033"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>
    <item>
        <ingredient id="70304" count="100"/> <!-- Tuna Fish -->
        <production id="91034"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>


    <item>
        <ingredient id="70304" count="15"/> <!-- Tuna Fish -->
        <production id="71438"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>


    <item>
        <ingredient id="70304" count="35"/> <!-- Tuna Fish -->
        <production id="49762"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>
    <item>
        <ingredient id="70304" count="25"/> <!-- Tuna Fish -->
        <production id="49763"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>

    <item>
        <ingredient id="70304" count="1000"/> <!-- Tuna Fish -->
        <production id="92472"/> <!-- Blessed Mysterious Soulshot (No-grade) -->
    </item>
</list>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/custom/10.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org ../multisell.xsd">
    <npcs>
        -1 <!-- CB -->
    </npcs>
    <item>
        <!-- Adena -->
        <ingredient count="2" id="57"/>
        <!-- Proof of Blood -->
        <production id="17"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="3" id="57"/>
        <!-- Proof of Alliance -->
        <production id="1341"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="5" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="1342"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="7" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="1343"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="9" id="57"/>
        <!-- Portal Stone -->
        <production id="1344"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="15" id="57"/>
        <!-- Proof of Blood -->
        <production id="1345"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="1200" id="57"/>
        <!-- Proof of Blood -->
        <production id="1458"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="4200" id="57"/>
        <!-- Proof of Blood -->
        <production id="1459"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="25000" id="57"/>
        <!-- Proof of Blood -->
        <production id="1460"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="100000" id="57"/>
        <!-- Proof of Blood -->
        <production id="1461"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="250000" id="57"/>
        <!-- Proof of Blood -->
        <production id="1462"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="1000" id="57"/>
        <!-- Proof of Alliance -->
        <production id="2130"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="3000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="2131"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="2132"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="3000000" id="57"/>
        <!-- Proof of Blood -->
        <production id="2133"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000000" id="57"/>
        <!-- Proof of Blood -->
        <production id="2134"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="2000" id="57"/>
        <!-- Proof of Blood -->
        <production id="1661"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="200" id="57"/>
        <!-- Proof of Blood -->
        <production id="5589"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="250" id="57"/>
        <!-- Proof of Alliance -->
        <production id="1785"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="400" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="3031"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="2000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="737"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="2000" id="57"/>
        <!-- Proof of Blood -->
        <production id="736"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="50000" id="57"/>
        <!-- Proof of Alliance -->
        <production id="1829"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="1830"/>
    </item>

    <item>
        <!-- Adena -->
        <ingredient count="1000000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="1538"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="1000000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="3936"/>
    </item>


    <item>
        <!-- Adena -->
        <ingredient count="150" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="1831"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="400" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="1832"/>
    </item>

    <item>
        <!-- Adena -->
        <ingredient count="4000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="1374"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="6000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="1375"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="6000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="6036"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="5591"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="50000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="5592"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="50" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="91912"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="1500" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="91252"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="200" id="57"/>
        <!-- Proof of Alliance -->
        <production id="5589"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="8000000" id="57"/>
        <!-- Proof of Aspiration -->
        <production id="5126"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="1500" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="4679"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="65000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="8615"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="20000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="49543"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="400000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="49684"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="210" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="2508"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="100000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="8871"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="150000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="49518"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="2000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="8618"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="2000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="8619"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="1000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="49758"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="50000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="1419"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="1000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="29676"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="90038"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="90039"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="90040"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="90041"/>
    </item>
    <item>
        <!-- Adena -->
        <ingredient count="10000000" id="57"/>
        <!-- Blood-stained Cloth -->
        <production id="90042"/>
    </item>
</list>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/1108.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd"
      apply-taxes="true">
    <npcs>
        30300 <!-- Pushkin -->
        30298 <!-- Pinter -->
        30317 <!-- Kluto -->
        30458 <!-- Poitan -->
        30471 <!-- Rupio -->
        30846 <!-- Wilbert -->
        30678 <!-- Helton -->
        30688 <!-- Duning -->
        31271 <!-- Hilda -->
        31583 <!-- Feynn -->
        30283 <!-- Altran -->
    </npcs>
    <item>
        <!-- Recipe: Braided Hemp -->
        <ingredient id="2135" consume="false"/>
        <!-- Stem -->
        <ingredient count="5" id="1864"/>
        <!-- Braided Hemp -->
        <production id="1878"/>
    </item>
    <item>
        <!-- Recipe: Cokes -->
        <ingredient id="2136" consume="false"/>
        <!-- Coal -->
        <ingredient count="3" id="1870"/>
        <!-- Charcoal -->
        <ingredient count="3" id="1871"/>
        <!-- Cokes -->
        <production id="1879"/>
    </item>
    <item>
        <!-- Recipe: Steel -->
        <ingredient id="2137" consume="false"/>
        <!-- Varnish -->
        <ingredient count="5" id="1865"/>
        <!-- Iron Ore -->
        <ingredient count="5" id="1869"/>
        <!-- Steel -->
        <production id="1880"/>
    </item>
    <item>
        <!-- Recipe: Coarse Bone Powder (100%) -->
        <ingredient id="2138" consume="false"/>
        <!-- Animal Bone -->
        <ingredient count="10" id="1872"/>
        <!-- Coarse Bone Powder -->
        <production id="1881"/>
    </item>
    <item>
        <!-- Recipe: Leather -->
        <ingredient id="1814" consume="false"/>
        <!-- Animal Skin -->
        <ingredient count="6" id="1867"/>
        <!-- Leather -->
        <production id="1882"/>
    </item>
    <item>
        <!-- Recipe: Steel Mold -->
        <ingredient id="2139" consume="false"/>
        <!-- Braided Hemp -->
        <ingredient count="5" id="1878"/>
        <!-- Iron Ore -->
        <ingredient count="5" id="1869"/>
        <!-- Coal -->
        <ingredient count="5" id="1870"/>
        <!-- Steel Mold -->
        <production id="1883"/>
    </item>
    <item>
        <!-- Recipe: Cord -->
        <ingredient id="1817" consume="false"/>
        <!-- Steel -->
        <ingredient count="2" id="1880"/>
        <!-- Thread -->
        <ingredient count="25" id="1868"/>
        <!-- Cord -->
        <production count="20" id="1884"/>
    </item>
    <item>
        <!-- Recipe: High-Grade Suede -->
        <ingredient id="2140" consume="false"/>
        <!-- Coarse Bone Powder -->
        <ingredient id="1881"/>
        <!-- Suede -->
        <ingredient count="3" id="1866"/>
        <!-- High-Grade Suede -->
        <production id="1885"/>
    </item>
    <item>
        <!-- Recipe: Silver Mold -->
        <ingredient id="2141" consume="false"/>
        <!-- Braided Hemp -->
        <ingredient count="5" id="1878"/>
        <!-- Cokes -->
        <ingredient count="5" id="1879"/>
        <!-- Silver Nugget -->
        <ingredient count="10" id="1873"/>
        <!-- Silver Mold -->
        <production id="1886"/>
    </item>
    <item>
        <!-- Recipe: Varnish of Purity -->
        <ingredient id="2142" consume="false"/>
        <!-- Coarse Bone Powder -->
        <ingredient count="3" id="1881"/>
        <!-- Varnish -->
        <ingredient count="3" id="1865"/>
        <!-- Stone of Purity -->
        <ingredient id="1875"/>
        <!-- Varnish of Purity -->
        <production id="1887"/>
    </item>
    <item>
        <!-- Recipe: Synthetic Cokes -->
        <ingredient id="2143" consume="false"/>
        <!-- Cokes -->
        <ingredient count="3" id="1879"/>
        <!-- Oriharukon Ore -->
        <ingredient id="1874"/>
        <!-- Synthetic Cokes -->
        <production id="1888"/>
    </item>
    <item>
        <!-- Recipe: Compound Braid -->
        <ingredient id="2144" consume="false"/>
        <!-- Braided Hemp -->
        <ingredient count="5" id="1878"/>
        <!-- Thread -->
        <ingredient count="5" id="1868"/>
        <!-- Compound Braid -->
        <production id="1889"/>
    </item>
    <item>
        <!-- Recipe: Mithril Alloy -->
        <ingredient id="2145" consume="false"/>
        <!-- Varnish of Purity -->
        <ingredient id="1887"/>
        <!-- Steel -->
        <ingredient count="2" id="1880"/>
        <!-- Mithril Ore -->
        <ingredient id="1876"/>
        <!-- Mithril Alloy -->
        <production id="1890"/>
    </item>
    <item>
        <!-- Recipe: Artisan's frame -->
        <ingredient id="2146" consume="false"/>
        <!-- Steel Mold -->
        <ingredient id="1883"/>
        <!-- Varnish of Purity -->
        <ingredient count="5" id="1887"/>
        <!-- Adamantite Nugget -->
        <ingredient count="10" id="1877"/>
        <!-- Artisan's Frame -->
        <production id="1891"/>
    </item>
    <item>
        <!-- Recipe: Blacksmith's frame -->
        <ingredient id="2147" consume="false"/>
        <!-- Silver Mold -->
        <ingredient id="1886"/>
        <!-- Varnish of Purity -->
        <ingredient count="5" id="1887"/>
        <!-- Mithril Ore -->
        <ingredient count="10" id="1876"/>
        <!-- Blacksmith's Frame -->
        <production id="1892"/>
    </item>
    <item>
        <!-- Recipe: Oriharukon -->
        <ingredient id="1825" consume="false"/>
        <!-- Synthetic Cokes -->
        <ingredient id="1888"/>
        <!-- Silver Nugget -->
        <ingredient count="12" id="1873"/>
        <!-- Oriharukon Ore -->
        <ingredient count="4" id="1874"/>
        <!-- Oriharukon -->
        <production id="1893"/>
    </item>
    <item>
        <!-- Recipe: Crafted Leather -->
        <ingredient id="2148" consume="false"/>
        <!-- Cord -->
        <ingredient count="4" id="1884"/>
        <!-- Leather -->
        <ingredient count="4" id="1882"/>
        <!-- Coal -->
        <ingredient count="4" id="1870"/>
        <!-- Crafted Leather -->
        <production id="1894"/>
    </item>
    <item>
        <!-- Recipe: Metallic Fiber -->
        <ingredient id="2149" consume="false"/>
        <!-- Cord -->
        <ingredient count="20" id="1884"/>
        <!-- Silver Nugget -->
        <ingredient count="15" id="1873"/>
        <!-- Metallic Fiber -->
        <production count="20" id="1895"/>
    </item>
    <item>
        <!-- Recipe: Metallic Thread(100%) -->
        <ingredient id="5472" consume="false"/>
        <!-- Thread -->
        <ingredient count="10" id="1868"/>
        <!-- Iron Ore -->
        <ingredient count="5" id="1869"/>
        <!-- Metallic Thread -->
        <production id="5549"/>
    </item>
    <item>
        <!-- Recipe: Metal Hardener (100%) -->
        <ingredient id="5231" consume="false"/>
        <!-- Stem -->
        <ingredient count="10" id="1864"/>
        <!-- Varnish -->
        <ingredient count="10" id="1865"/>
        <!-- Iron Ore -->
        <ingredient count="10" id="1869"/>
        <!-- Metal Hardener -->
        <production id="5220"/>
    </item>
    <item>
        <!-- Recipe: Durable Metal Plate(100%) -->
        <ingredient id="5473" consume="false"/>
        <!-- Metallic Thread -->
        <ingredient count="5" id="5549"/>
        <!-- Mithril Ore -->
        <ingredient count="5" id="1876"/>
        <!-- Durable Metal Plate -->
        <production id="5550"/>
    </item>
    <item>
        <!-- Cord -->
        <ingredient count="40" id="1884"/>
        <!-- Durable Metal Plate -->
        <ingredient count="10" id="5550"/>
        <!-- Adamantite Nugget -->
        <ingredient count="15" id="1877"/>
        <!-- Reorin's Mold -->
        <production id="5551"/>
    </item>
    <item>
        <!-- Artisan's Frame -->
        <ingredient id="1891"/>
        <!-- Mold Hardener -->
        <ingredient count="10" id="4041"/>
        <!-- Enria -->
        <ingredient count="5" id="4042"/>
        <!-- Warsmith's Mold -->
        <production id="5552"/>
    </item>
    <item>
        <!-- Maestro Anvil Lock -->
        <ingredient count="3" id="4046"/>
        <!-- Mold Lubricant -->
        <ingredient count="20" id="4040"/>
        <!-- Thons -->
        <ingredient count="10" id="4044"/>
        <!-- Adena -->
        <ingredient count="541824" id="57"/>
        <!-- Arcsmith's Anvil -->
        <production id="5553"/>
    </item>
    <item>
        <!-- Maestro Holder -->
        <ingredient count="2" id="4045"/>
        <!-- Mold Glue -->
        <ingredient count="10" id="4039"/>
        <!-- Thread -->
        <ingredient count="20" id="1868"/>
        <!-- Warsmith's Holder -->
        <production id="5554"/>
    </item>
</list>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/4676.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd"
      apply-taxes="true">
    <!-- Immortal: Update 270 Prot -->
    <npcs>
        30020 <!-- Baggins -->
    </npcs>
    <item>
        <ingredient id="71078"/> <!-- Talisman of Authority Fragment -->
        <production id="71080"/> <!-- Talisman of Authority Lv. 1 -->
    </item>
    <item>
        <ingredient id="71084"/> <!-- Talisman of Authority Lv. 5 -->
        <ingredient count="3" id="71078"/> <!-- Talisman of Authority Fragment -->
        <ingredient count="20000000" id="57"/> <!-- Adena -->
        <production id="71085"/> <!-- Noble Talisman of Authority Lv. 1 -->
    </item>
    <item>
        <ingredient id="71089"/> <!-- Noble Talisman of Authority Lv. 5 -->
        <ingredient count="6" id="71078"/> <!-- Talisman of Authority Fragment -->
        <ingredient count="40000000" id="57"/> <!-- Adena -->
        <production id="71090"/> <!-- Radiant Talisman of Authority Lv. 1 -->
    </item>
</list>
