=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/multisell.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="npcs" type="intList" minOccurs="0"/>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ingredient" type="Ingredient" minOccurs="0" maxOccurs="unbounded"/>
                            <xs:element name="production" type="Product" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="apply-taxes" type="xs:boolean" default="false"/>
            <xs:attribute name="gm-only" type="xs:boolean" default="false"/>
            <xs:attribute name="chance-based" type="xs:boolean" default="false"/>
            <xs:attribute name="maintain-enchantment" type="xs:boolean" default="false"/>
            <xs:attribute name="ingredient-multiplier" type="xs:double" default="1"/>
            <xs:attribute name="product-multiplier" type="xs:double" default="1"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Ingredient">
        <xs:complexContent>
            <xs:extension base="EnchantedItem">
                <xs:attribute name="consume" type="xs:boolean" default="true"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Product">
        <xs:complexContent>
            <xs:extension base="EnchantedItem">
                <xs:attribute name="chance" type="xs:double" default="0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/9000.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd"
      apply-taxes="true">
    <npcs>
        30026 <!-- Altran -->
        30031 <!-- Pinter -->
        30037 <!-- Pushkin -->
        30066 <!-- Karrod -->
        30070 <!-- Kluto -->
        30109 <!-- Aios -->
        30115 <!-- Poitan -->
        30120 <!-- Rupio -->
        30154 <!-- Brunon -->
        30174 <!-- Silvera -->
        30175 <!-- Sumari -->
        30176 <!-- Duning -->
        30187 <!-- Altran -->
        30191 <!-- Pinter -->
        30195 <!-- Pushkin -->
        30288 <!-- Karrod -->
        30289 <!-- Kluto -->
        30290 <!-- Aios -->
        30297 <!-- Poitan -->
        30358 <!-- Rupio -->
        30373 <!-- Brunon -->
        30462 <!-- Silvera -->
        30474 <!-- Sumari -->
        30498 <!-- Duning -->
        30499 <!-- Duning -->
        30500 <!-- Altran -->
        30503 <!-- Pinter -->
        30504 <!-- Pushkin -->
        30505 <!-- Karrod -->
        30508 <!-- Kluto -->
        30511 <!-- Aios -->
        30512 <!-- Poitan -->
        30513 <!-- Rupio -->
        30520 <!-- Brunon -->
        30525 <!-- Silvera -->
        30565 <!-- Sumari -->
        30594 <!-- Duning -->
        30595 <!-- Altran -->
        30676 <!-- Pinter -->
        30677 <!-- Pushkin -->
        30681 <!-- Karrod -->
        30685 <!-- Kluto -->
        30687 <!-- Aios -->
        30689 <!-- Poitan -->
        30694 <!-- Rupio -->
        30699 <!-- Brunon -->
        30704 <!-- Silvera -->
        30845 <!-- Sumari -->
        30847 <!-- Duning -->
        30849 <!-- Duning -->
        30854 <!-- Silvera -->
        30857 <!-- Sumari -->
        30862 <!-- Duning -->
        30865 <!-- Duning -->
    </npcs>
    <item>
        <ingredient id="70024"/> <!-- Daily Coin -->
        <production id="1864" count="10" chance="100"/> <!-- Stem -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1865" count="10" chance="100"/> <!-- Varnish -->
    </item>
    <item>
        <ingredient id="70024" count="3"/> <!-- Daily Coin -->
        <production id="1866" count="10" chance="100"/> <!-- Suede -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1867" count="10" chance="100"/> <!-- Animal Skin -->
    </item>
    <item>
        <ingredient id="70024"/> <!-- Daily Coin -->
        <production id="1868" count="10" chance="100"/> <!-- Thread -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1869" count="10" chance="100"/> <!-- Iron Ore -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1870" count="10" chance="100"/> <!-- Coal -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1871" count="10" chance="100"/> <!-- Charcoal -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1872" count="10" chance="100"/> <!-- Animal Bone -->
    </item>
    <item>
        <ingredient id="70024" count="5"/> <!-- Daily Coin -->
        <production id="1873" count="10" chance="100"/> <!-- Silver Nugget -->
    </item>
    <item>
        <ingredient id="70024" count="3"/> <!-- Daily Coin -->
        <production id="1874" chance="100"/> <!-- Oriharukon Ore -->
    </item>
    <item>
        <ingredient id="70024" count="3"/> <!-- Daily Coin -->
        <production id="1875" chance="100"/> <!-- Stone of Purity -->
    </item>
    <item>
        <ingredient id="70024"/> <!-- Daily Coin -->
        <production id="1876" chance="100"/> <!-- Mithril Ore -->
    </item>
    <item>
        <ingredient id="70024" count="5"/> <!-- Daily Coin -->
        <production id="1877" chance="100"/> <!-- Adamantite Nugget -->
    </item>
    <item>
        <ingredient id="70024" count="5"/> <!-- Daily Coin -->
        <production id="1878" chance="100"/> <!-- Durable Braid -->
    </item>
    <item>
        <ingredient id="70024"/> <!-- Daily Coin -->
        <production id="1879" chance="100"/> <!-- Cokes -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1880" chance="100"/> <!-- Steel -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1881" chance="100"/> <!-- Coarse Bone Powder -->
    </item>
    <item>
        <ingredient id="70024"/> <!-- Daily Coin -->
        <production id="1882" chance="100"/> <!-- Leather -->
    </item>
    <item>
        <ingredient id="70024" count="5"/> <!-- Daily Coin -->
        <production id="1883" chance="100"/> <!-- Steel Mold -->
    </item>
    <item>
        <ingredient id="70024" count="3"/> <!-- Daily Coin -->
        <production id="1884" count="10" chance="100"/> <!-- Cord -->
    </item>
    <item>
        <ingredient id="70024" count="2"/> <!-- Daily Coin -->
        <production id="1885" chance="100"/> <!-- High-Grade Suede -->
    </item>
    <item>
        <ingredient id="70024" count="14"/> <!-- Daily Coin -->
        <production id="1886" chance="100"/> <!-- Silver Mold -->
    </item>
    <item>
        <ingredient id="70024" count="8"/> <!-- Daily Coin -->
        <production id="1887" chance="100"/> <!-- Varnish of Purity -->
    </item>
    <item>
        <ingredient id="70024" count="7"/> <!-- Daily Coin -->
        <production id="1888" chance="100"/> <!-- Synthetic Cokes -->
    </item>
    <item>
        <ingredient id="70024" count="3"/> <!-- Daily Coin -->
        <production id="1889" chance="100"/> <!-- Synthetic Braid -->
    </item>
    <item>
        <ingredient id="70024" count="13"/> <!-- Daily Coin -->
        <production id="1890" chance="100"/> <!-- Mithril Alloy -->
    </item>
    <item>
        <ingredient id="70024" count="95"/> <!-- Daily Coin -->
        <production id="1891" chance="100"/> <!-- Artisan's frame -->
    </item>
    <item>
        <ingredient id="70024" count="64"/> <!-- Daily Coin -->
        <production id="1892" chance="100"/> <!-- Blacksmith's frame -->
    </item>
    <item>
        <ingredient id="70024" count="25"/> <!-- Daily Coin -->
        <production id="1893" chance="100"/> <!-- Oriharukon -->
    </item>
    <item>
        <ingredient id="70024" count="6"/> <!-- Daily Coin -->
        <production id="1894" chance="100"/> <!-- Crafted Leather -->
    </item>
    <item>
        <ingredient id="70024" count="7"/> <!-- Daily Coin -->
        <production id="1895" count="10" chance="100"/> <!-- Metallic Fiber -->
    </item>
    <item>
        <ingredient id="70024" count="6"/> <!-- Daily Coin -->
        <production id="4039" chance="100"/> <!-- Mold Glue -->
    </item>
    <item>
        <ingredient id="70024" count="10"/> <!-- Daily Coin -->
        <production id="4040" chance="100"/> <!-- Mold Lubricant -->
    </item>
    <item>
        <ingredient id="70024" count="23"/> <!-- Daily Coin -->
        <production id="4041" chance="100"/> <!-- Mold Hardener -->
    </item>
    <item>
        <ingredient id="70024" count="12"/> <!-- Daily Coin -->
        <production id="4042" chance="100"/> <!-- Enria -->
    </item>
    <item>
        <ingredient id="70024" count="6"/> <!-- Daily Coin -->
        <production id="4043" chance="100"/> <!-- Asofe -->
    </item>
    <item>
        <ingredient id="70024" count="6"/> <!-- Daily Coin -->
        <production id="4044" chance="100"/> <!-- Thons -->
    </item>
    <item>
        <ingredient id="70024" count="411"/> <!-- Daily Coin -->
        <production id="4045" chance="100"/> <!-- Maestro Holder -->
    </item>
    <item>
        <ingredient id="70024" count="90"/> <!-- Daily Coin -->
        <production id="4046" chance="100"/> <!-- Maestro Anvil Lock -->
    </item>
    <item>
        <ingredient id="70024" count="710"/> <!-- Daily Coin -->
        <production id="4047" chance="100"/> <!-- Craftsman Mold -->
    </item>
    <item>
        <ingredient id="70024" count="154"/> <!-- Daily Coin -->
        <production id="4048" chance="100"/> <!-- Maestro Mold -->
    </item>

    <item>
        <ingredient id="29978"/> <!-- Bracelet of Duty Lv.1 -->
        <ingredient id="70024" count="300"/> <!-- Daily Coin -->
        <production id="29979" chance="100"/> <!-- Bracelet of Duty Lv.2 -->
    </item>
    <item>
        <ingredient id="29979"/> <!-- Bracelet of Duty Lv.2 -->
        <ingredient id="70024" count="500"/> <!-- Daily Coin -->
        <production id="29980" chance="100"/> <!-- Bracelet of Duty Lv.3 -->
    </item>
    <item>
        <ingredient id="29980"/> <!-- Bracelet of Duty Lv.3 -->
        <ingredient id="70024" count="700"/> <!-- Daily Coin -->
        <production id="29981" chance="100"/> <!-- Bracelet of Duty Lv.4 -->
    </item>
    <item>
        <ingredient id="29981"/> <!-- Bracelet of Duty Lv.4 -->
        <ingredient id="70024" count="1000"/> <!-- Daily Coin -->
        <production id="29982" chance="100"/> <!-- Bracelet of Duty Lv.5 -->
    </item>
    <item>
        <ingredient id="29982"/> <!-- Bracelet of Duty Lv.5 -->
        <ingredient id="70024" count="3500"/> <!-- Daily Coin -->
        <production id="70922" chance="100"/> <!-- Bracelet of Duty Lv.6 -->
    </item>
    <item>
        <ingredient id="70024" count="10"/> <!-- Daily Coin -->
        <production id="90907" count="10" chance="100"/> <!-- Cupon -->
    </item>
</list>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/3426201.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd"
      chance-based="true">
    <npcs>
        34262 <!-- Sibi Manager -->
    </npcs>
    <item>
        <!-- Sibi's Coin -->
        <ingredient id="49783" count="20"/>
        <production id="32253"/> <!-- Infinite Mithril Quiver -->
        <production id="32253" chance="1"/> <!-- Infinite Mithril Quiver -->
        <production id="32249" chance="1"/> <!-- Infinite Wooden Quiver -->
        <production id="32250" chance="1"/> <!-- Infinite Bone Quiver -->
        <production id="32251" chance="1"/> <!-- Infinite Steel Quiver -->
        <production id="32252" chance="1"/> <!-- Infinite Silver Quiver -->
        <production id="17" count="100" chance="19"/> <!-- Wooden Arrow -->
        <production id="1341" count="200" chance="19"/> <!-- Bone Arrow -->
        <production id="1342" count="100" chance="19"/> <!-- Steel Arrow -->
        <production id="1343" count="100" chance="19"/> <!-- Silver Arrow -->
        <production id="1344" count="100" chance="19"/> <!-- Mithril Arrow -->
    </item>
</list>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/4707.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd">
    <!-- 272 Prot -->
    <npcs>
        -1 <!-- Dimensional Merchant / Everywhere -->
    </npcs>
    <item>
        <!-- Ticket -->
        <ingredient id="90907"/>
        <!-- Soulshots  -->
        <production count="500" id="91927"/>
    </item>

    <item>
        <!-- Ticket -->
        <ingredient id="90907"/>
        <!-- Blessed Spiritshot -->
        <production count="287" id="91928"/>
    </item>
    <item>
        <!-- Ticket -->
        <ingredient id="90907"/>
        <!-- Blessed Spiritshot -->
        <production count="134" id="91930"/>
    </item>
</list>

=== LegacyofAden/L2jOrg-1/Datapack/data/multisell/10001.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://l2j.org"
      xsi:schemaLocation="http://l2j.org multisell.xsd">
    <npcs>
        30841 <!-- Carson -->
    </npcs>
    <item>
        <ingredient id="93974"/> <!-- Ticket -->
        <production id="93968" count="10"/> <!-- Due -->
    </item>
    <item>
        <ingredient id="93974"/> <!-- Ticket -->
        <production id="93969" count="10"/> <!-- Due -->
    </item>
    <item>
        <ingredient id="93974"/> <!-- Ticket -->
        <production id="93970" count="10"/> <!-- Due -->
    </item>
    <item>
        <ingredient id="93974"/> <!-- Ticket -->
        <production id="93971" count="10"/> <!-- Due -->
    </item>
    <item>
        <ingredient id="93974"/> <!-- Ticket -->
        <production id="93972" count="10"/> <!-- Due -->
    </item>
    <item>
        <ingredient id="93974"/> <!-- Ticket -->
        <production id="93973" count="10"/> <!-- Due -->
    </item>
</list>
