=== LegacyofAden/L2jOrg-1/Datapack/data/mapregion/map-region.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../xsd/common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="region" type="Region" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" default="true" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Region">
		<xs:sequence>
			<xs:element name="respawn-point" type="Respawn" maxOccurs="unbounded"/>
			<xs:element name="map" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="x" type="xs:integer" use="required" />
					<xs:attribute name="y" type="xs:integer" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element name="banned" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="point" type="xs:token" use="required" />
					<xs:attribute name="race" type="Race" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="bbs" type="xs:token" use="required" />
		<xs:attribute name="loc" type="xs:positiveInteger" use="required" />
		<xs:attribute name="name" type="xs:token" use="required" />
		<xs:attribute name="town" type="xs:token" use="required" />
	</xs:complexType>

	<xs:complexType name="Respawn">
		<xs:complexContent>
			<xs:extension base="Location">
				<xs:attribute name="chaotic" type="xs:boolean" default="false"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== LegacyofAden/L2jOrg-1/Datapack/data/mapregion/hunters-town.xml
<?xml version="1.0" encoding="UTF-8"?>

<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org map-region.xsd">
	<!-- Hunter Town -->
	<region name="hunter_town" town="Hunters Village" loc="923" bbs="11">
		<respawn-point x="116127" y="76015" z="-2729" />
		<respawn-point x="115683" y="77610" z="-2650" />
		<respawn-point x="117304" y="76318" z="-2670" />
		<respawn-point x="119862" y="76603" z="-2220" />
		<respawn-point x="117671" y="78998" z="-2210" />
		<respawn-point x="117189" y="78952" z="-2210" />
		<respawn-point x="115861" y="75200" z="-2550" />
		<respawn-point x="118275" y="74859" z="-2557" />
		<respawn-point x="118229" y="74677" z="-2450" />
		<respawn-point x="115685" y="75072" z="-2550" />
		<respawn-point x="116704" y="75695" z="-2680" />
		<respawn-point x="116737" y="76738" z="-2650" />
		<respawn-point x="115193" y="77594" z="-2670" />
		<respawn-point x="116158" y="77443" z="-2660" />
		<respawn-point x="122098" y="70373" z="-2864" chaotic="true" />
		<respawn-point x="118674" y="71218" z="-2743" chaotic="true" />
		<respawn-point x="118040" y="67175" z="-2905" chaotic="true" />
		<respawn-point x="119300" y="70660" z="-2850" chaotic="true" />
		<respawn-point x="118851" y="70566" z="-2800" chaotic="true" />
		<respawn-point x="112655" y="70976" z="-3122" chaotic="true" />
		<respawn-point x="119712" y="66376" z="-2960" chaotic="true" />
		<respawn-point x="107511" y="82890" z="-2515" chaotic="true" />
		<respawn-point x="105702" y="82773" z="-2803" chaotic="true" />
		<respawn-point x="104257" y="82194" z="-2581" chaotic="true" />
		<respawn-point x="104474" y="81109" z="-2651" chaotic="true" />
		<map x="20" y="10" />
		<map x="23" y="20" />
		<map x="23" y="19" />
		<map x="24" y="20" />
		<map x="25" y="20" />
	</region>
</list>

=== LegacyofAden/L2jOrg-1/Datapack/data/mapregion/dwarf-town.xml
<?xml version="1.0" encoding="UTF-8"?>

<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xmlns="http://l2j.org"
	  xsi:schemaLocation="http://l2j.org map-region.xsd">
	<region name="dwarf_town" town="Dwarven Town" loc="921" bbs="9">
		<respawn-point x="116176" y="-182448" z="-1400" />
		<respawn-point x="116476" y="-182904" z="-1500" />
		<respawn-point x="115248" y="-178816" z="-850" />
		<respawn-point x="116352" y="-179264" z="-1000" />
		<respawn-point x="115271" y="-178561" z="-820" />
		<respawn-point x="115249" y="-177859" z="-820" />
		<respawn-point x="115485" y="-178077" z="-820" />
		<respawn-point x="115790" y="-179146" z="-890" />
		<respawn-point x="116507" y="-179597" z="-1000" />
		<respawn-point x="116725" y="-180147" z="-1000" />
		<respawn-point x="116738" y="-181494" z="-1300" />
		<respawn-point x="116775" y="-182367" z="-1400" />
		<respawn-point x="116587" y="-183032" z="-1400" />
		<respawn-point x="116321" y="-182734" z="-1400" />
		<respawn-point x="118160" y="-179328" z="-1578" chaotic="true" />
		<respawn-point x="119024" y="-180208" z="-2180" chaotic="true" />
		<respawn-point x="119728" y="-180912" z="-2649" chaotic="true" />
		<respawn-point x="119776" y="-181968" z="-2948" chaotic="true" />
		<respawn-point x="119392" y="-183968" z="-3125" chaotic="true" />
		<respawn-point x="119520" y="-184928" z="-3196" chaotic="true" />
		<respawn-point x="119568" y="-186016" z="-3220" chaotic="true" />
		<respawn-point x="119984" y="-187312" z="-3260" chaotic="true" />
		<respawn-point x="119632" y="-188352" z="-3260" chaotic="true" />
		<respawn-point x="119264" y="-188736" z="-3203" chaotic="true" />
		<respawn-point x="118656" y="-187760" z="-2828" chaotic="true" />
		<map x="23" y="10" />
		<map x="23" y="11" />
		<map x="23" y="12" />
		<map x="24" y="10" />
		<map x="24" y="11" />
		<map x="24" y="12" />
		<map x="25" y="10" />
		<map x="25" y="11" />
		<map x="25" y="12" />
	</region>
	<!-- Quarry -->
	<region name="Quarry" town="Dwarven Town" loc="921" bbs="9">
		<respawn-point x="108644" y="-173947" z="-400" />
		<respawn-point x="108678" y="-174002" z="-400" />
		<respawn-point x="108505" y="-173964" z="-400" />
		<respawn-point x="108512" y="-174026" z="-400" />
		<respawn-point x="108549" y="-174075" z="-400" />
		<respawn-point x="108576" y="-174122" z="-400" />
		<respawn-point x="118160" y="-179328" z="-1578" chaotic="true" />
		<respawn-point x="119024" y="-180208" z="-2180" chaotic="true" />
		<respawn-point x="119728" y="-180912" z="-2649" chaotic="true" />
		<respawn-point x="119776" y="-181968" z="-2948" chaotic="true" />
		<respawn-point x="119392" y="-183968" z="-3125" chaotic="true" />
		<respawn-point x="119520" y="-184928" z="-3196" chaotic="true" />
		<respawn-point x="119568" y="-186016" z="-3220" chaotic="true" />
		<respawn-point x="119984" y="-187312" z="-3260" chaotic="true" />
		<respawn-point x="119632" y="-188352" z="-3260" chaotic="true" />
		<respawn-point x="119264" y="-188736" z="-3203" chaotic="true" />
		<respawn-point x="118656" y="-187760" z="-2828" chaotic="true" />
	</region>
</list>
