=== LegacyofAden/L2jOrg-1/Datapack/data/zones/zones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../xsd/common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="zone" type="Zone" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" default="true" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="form" type="ZoneForm"/>
	<xs:element name="cube" type="Cube" substitutionGroup="form"/>
	<xs:element name="cylinder" type="Cylinder" substitutionGroup="form"/>
	<xs:element name="polygon" type="Polygon" substitutionGroup="form"/>


	<xs:complexType name="Zone">
		<xs:sequence>
			<xs:element ref="form"/>
			<xs:element name="property" type="Property" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="respawn" type="Respawn" maxOccurs="unbounded" minOccurs="0"/>
			<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger"/>
		<xs:attribute name="name" type="xs:normalizedString"/>
		<xs:attribute name="type" type="xs:token" use="required"/>
	</xs:complexType>

	<xs:complexType name="Property">
		<xs:attribute name="name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="affectedLvlMin" />
					<xs:enumeration value="affectedRace" />
					<xs:enumeration value="allowStore" />
					<xs:enumeration value="bossId" />
					<xs:enumeration value="castleId" />
					<xs:enumeration value="chance" />
					<xs:enumeration value="clanHallId" />
					<xs:enumeration value="dmgHPSec" />
					<xs:enumeration value="default_enabled" />
					<xs:enumeration value="domainId" />
					<xs:enumeration value="enterMsgId" />
					<xs:enumeration value="eventId" />
					<xs:enumeration value="fortId" />
					<xs:enumeration value="HpRegenBonus" />
					<xs:enumeration value="initialDelay" />
					<xs:enumeration value="instanceId" />
					<xs:enumeration value="instanceTemplate" />
					<xs:enumeration value="InvadeTime" />
					<xs:enumeration value="leaveMsgId" />
					<xs:enumeration value="maxDynamicSkillCount" />
					<xs:enumeration value="move_bonus" />
					<xs:enumeration value="MpRegenBonus" />
					<xs:enumeration value="NoBookmark" />
					<xs:enumeration value="NoItemDrop" />
					<xs:enumeration value="oustX" />
					<xs:enumeration value="oustY" />
					<xs:enumeration value="oustZ" />
					<xs:enumeration value="residenceId" />
					<xs:enumeration value="residenceZoneId" />
					<xs:enumeration value="restartAllowedTime" />
					<xs:enumeration value="restartTime" />
					<xs:enumeration value="reuse" />
					<xs:enumeration value="showDangerIcon" />
					<xs:enumeration value="skillIdLvl" />
					<xs:enumeration value="spawnMaxX" />
					<xs:enumeration value="spawnMaxY" />
					<xs:enumeration value="spawnMaxZ" />
					<xs:enumeration value="spawnMinX" />
					<xs:enumeration value="spawnMinY" />
					<xs:enumeration value="spawnMinZ" />
					<xs:enumeration value="spawnZ" />
					<xs:enumeration value="targetClass" />
					<xs:enumeration value="taxById" />
					<xs:enumeration value="territoryId" />
					<xs:enumeration value="townId" />
					<xs:enumeration value="mapId" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="value" type="xs:token" use="required" />
	</xs:complexType>

	<xs:complexType name="Spawn">
		<xs:complexContent>
			<xs:extension base="Location">
				<xs:attribute name="type" type="SpawnType" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="SpawnType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="banish" />
			<xs:enumeration value="blueBanishPoint" />
			<xs:enumeration value="blueStartPoint" />
			<xs:enumeration value="challenger" />
			<xs:enumeration value="chaotic" />
			<xs:enumeration value="entrance" />
			<xs:enumeration value="other" />
			<xs:enumeration value="redBanishPoint" />
			<xs:enumeration value="redStartPoint" />
			<xs:enumeration value="spectatorSpawn" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Respawn">
		<xs:attribute name="region" type="xs:token" use="required" />
		<xs:attribute name="race" type="Race" use="required" />
	</xs:complexType>

	<xs:complexType name="ZoneForm" abstract="true">
		<xs:attribute name="min-z" type="xs:integer" use="required" />
		<xs:attribute name="max-z" type="xs:integer" use="required" />
	</xs:complexType>

	<xs:complexType name="Cube">
		<xs:complexContent>
			<xs:extension base="ZoneForm">
				<xs:sequence>
					<xs:element name="point" type="Location" minOccurs="2" maxOccurs="2"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Cylinder">
		<xs:complexContent>
			<xs:extension base="ZoneForm">
				<xs:sequence>
					<xs:element name="point" type="Location"/>
				</xs:sequence>
				<xs:attribute name="radius" type="xs:positiveInteger" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Polygon">
		<xs:complexContent>
			<xs:extension base="ZoneForm">
				<xs:sequence>
					<xs:element name="point" type="Location" minOccurs="3" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== LegacyofAden/L2jOrg-1/Datapack/data/zones/zone.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org zones.xsd">
    <!-- NOT USED! -->
	<zone name="Seed of Annihilation 1" id="60006" type="org.l2j.gameserver.world.zone.type.EffectZone">
        <polygon min-z="-10700" max-z="-10100">
            <point x="-180000" y="183000"/>
            <point x="-178300" y="184666"/>
            <point x="-173000" y="184666"/>
            <point x="-173000" y="174500"/>
            <point x="-187350" y="174500"/>
            <point x="-187350" y="184666"/>
            <point x="-182000" y="184666"/>
            <point x="-180500" y="183000"/>
        </polygon>
        <property name="maxDynamicSkillCount" value="1"/>
        <property name="showDangerIcon" value="false"/>
        <property name="initialDelay" value="1000"/>
        <property name="reuse" value="3000"/>
    </zone>

    <!-- <zone name="Seed of Annihilation 2" id="60007" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <polygon min-z="-15900" max-z="-14950"> -->
            <!-- <point x="-180000" y="182500"/> -->
            <!-- <point x="-178800" y="183500"/> -->
            <!-- <point x="-176500" y="183500"/> -->
            <!-- <point x="-176500" y="187000"/> -->
            <!-- <point x="-173000" y="187000"/> -->
            <!-- <point x="-173000" y="175000"/> -->
            <!-- <point x="-187500" y="175000"/> -->
            <!-- <point x="-187500" y="187600"/> -->
            <!-- <point x="-183500" y="187600"/> -->
            <!-- <point x="-183500" y="183500"/> -->
            <!-- <point x="-181000" y="183500"/> -->
            <!-- <point x="-180500" y="182500"/> -->
        <!-- </polygon> -->
        <!-- <property name="maxDynamicSkillCount" value="1"/> -->
        <!-- <property name="showDangerIcon" value="false"/> -->
        <!-- <property name="initialDelay" value="1000"/> -->
        <!-- <property name="reuse" value="3000"/> -->
    <!-- </zone> -->
    <!-- <zone name="Seed of Annihilation 3" id="60008" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <polygon min-z="-12850" max-z="-10800"> -->
            <!-- <point x="-212800" y="182800"/> -->
            <!-- <point x="-211000" y="185000"/> -->
            <!-- <point x="-205000" y="185000"/> -->
            <!-- <point x="-205000" y="172000"/> -->
            <!-- <point x="-221000" y="172000"/> -->
            <!-- <point x="-221000" y="187000"/> -->
            <!-- <point x="-216000" y="187000"/> -->
            <!-- <point x="-213500" y="182800"/> -->
        <!-- </polygon> -->
        <!-- <property name="maxDynamicSkillCount" value="1"/> -->
        <!-- <property name="showDangerIcon" value="false"/> -->
        <!-- <property name="initialDelay" value="1000"/> -->
        <!-- <property name="reuse" value="3000"/> -->
    <!-- </zone> -->
	
	<!-- NOT USED! -->
    <!-- (vertices, min Z and Max Z are estimated) -->
    <!-- <zone name="Den of Evil 1" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-2300" max-z="-2100" radius="750"> -->
            <!-- <point x="74313" y="-116888"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 2" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-2400" max-z="-2200" radius="850"> -->
            <!-- <point x="63170" y="-106621"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 3" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-1200" max-z="-1000" radius="1200"> -->
            <!-- <point x="68030" y="-107150"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 4" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-3100" max-z="-2900" radius="1200"> -->
            <!-- <point x="62351" y="-117376"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 5" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-2200" max-z="-2000" radius="1200"> -->
            <!-- <point x="68100" y="-116006"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 6" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-2600" max-z="-2400" radius="1200"> -->
            <!-- <point x="69911" y="-118790"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 7" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-3000" max-z="-2800" radius="1200"> -->
            <!-- <point x="67520" y="-122211"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 8" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-3100" max-z="-2900" radius="1500"> -->
            <!-- <point x="74325" y="-121296"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 9" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-3100" max-z="-2850" radius="1200"> -->
            <!-- <point x="70788" y="-125554"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 10" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-3200" max-z="-3000" radius="1200"> -->
            <!-- <point x="76155" y="-127355"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
    <!-- <zone name="Den of Evil 11" type="org.l2j.gameserver.world.zone.type.EffectZone"> -->
        <!-- <cylinder min-z="-3400" max-z="-3200" radius="750"> -->
            <!-- <point x="71543" y="-128820"/> -->
        <!-- </cylinder> -->
        <!-- <property name="reuse" value="9000"/> -->
        <!-- <property name="targetClass" value="Creature"/> -->
    <!-- </zone> -->
</list>
