=== LegacyofAden/L2jOrg-1/Datapack/data/upgrade/upgrade.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="rare-upgrade" type="RareUpgrade" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="upgrade" type="CommonUpgrade" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="RareUpgrade">
        <xs:complexContent>
            <xs:extension base="Upgrade">
                <xs:attribute name="result" type="xs:int" use="required"/>
                <xs:attribute name="result-enchantment" type="xs:byte" default="0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="CommonUpgrade">
        <xs:complexContent>
            <xs:extension base="Upgrade">
                <xs:sequence>
                    <xs:element name="bonus-item" type="ItemInfo" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="item-on-fail" type="ItemInfo" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="result" type="EnchantedItem" maxOccurs="unbounded"/>
                </xs:sequence>
                <xs:attribute name="type" type="UpgradeType" default="NORMAL"/>
                <xs:attribute name="chance" type="xs:int" default="100"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Upgrade" abstract="true">
        <xs:sequence>
            <xs:element name="material" type="ItemInfo" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="item" type="xs:int" use="required"/>
        <xs:attribute name="enchantment" type="xs:byte" use="required"/>
        <xs:attribute name="commission" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:simpleType name="UpgradeType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NORMAL"/>
            <xs:enumeration value="SPECIAL"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== LegacyofAden/L2jOrg-1/Datapack/data/upgrade/11300-11399.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org upgrade.xsd">

    <upgrade id="11300" item="855" enchantment="9" commission="5587200">
        <material id="1459" count="776"/>
        <material id="91543" count="5"/>
        <result id="864" enchant="8"/>
    </upgrade>

    <upgrade id="11301" item="855" enchantment="10" commission="9312000">
        <material id="1459" count="1294"/>
        <material id="91543" count="8"/>
        <result id="864" enchant="9"/>
    </upgrade>

    <upgrade id="11302" item="855" enchantment="11" commission="10243200">
        <material id="1459" count="1423"/>
        <material id="91543" count="9"/>
        <result id="864" enchant="10"/>
    </upgrade>

    <upgrade id="11303" item="855" enchantment="12" commission="11174400">
        <material id="1459" count="1552"/>
        <material id="91543" count="10"/>
        <result id="864" enchant="11"/>
    </upgrade>

    <upgrade id="11304" item="855" enchantment="13" commission="13036800">
        <material id="1459" count="1811"/>
        <material id="91543" count="12"/>
        <result id="864" enchant="12"/>
    </upgrade>

    <upgrade id="11305" item="855" enchantment="14" commission="14899200">
        <material id="1459" count="2070"/>
        <material id="91543" count="13"/>
        <result id="864" enchant="13"/>
    </upgrade>

    <upgrade id="11306" item="855" enchantment="15" commission="16761600">
        <material id="1459" count="2328"/>
        <material id="91543" count="15"/>
        <result id="864" enchant="14"/>
    </upgrade>

    <upgrade id="11307" item="855" enchantment="16" commission="18624000">
        <material id="1459" count="2587"/>
        <material id="91543" count="17"/>
        <result id="864" enchant="15"/>
    </upgrade>

    <upgrade id="11308" item="855" enchantment="17" commission="22348800">
        <material id="1459" count="3104"/>
        <material id="91543" count="20"/>
        <result id="864" enchant="16"/>
    </upgrade>

    <upgrade id="11309" item="855" enchantment="18" commission="26073600">
        <material id="1459" count="3622"/>
        <material id="91543" count="23"/>
        <result id="864" enchant="17"/>
    </upgrade>

    <upgrade id="11310" item="855" enchantment="19" commission="29798400">
        <material id="1459" count="4139"/>
        <material id="91543" count="27"/>
        <result id="864" enchant="18"/>
    </upgrade>

    <upgrade id="11311" item="855" enchantment="20" commission="37248000">
        <material id="1459" count="5174"/>
        <material id="91543" count="33"/>
        <result id="864" enchant="19"/>
    </upgrade>

    <upgrade id="11312" item="857" enchantment="8" commission="3724800">
        <material id="1459" count="518"/>
        <material id="91543" count="3"/>
        <result id="864" enchant="7"/>
    </upgrade>

    <upgrade id="11313" item="857" enchantment="9" commission="5587200">
        <material id="1459" count="776"/>
        <material id="91543" count="5"/>
        <result id="864" enchant="8"/>
    </upgrade>

    <upgrade id="11314" item="857" enchantment="10" commission="9312000">
        <material id="1459" count="1294"/>
        <material id="91543" count="8"/>
        <result id="864" enchant="9"/>
    </upgrade>

    <upgrade id="11315" item="857" enchantment="11" commission="10243200">
        <material id="1459" count="1423"/>
        <material id="91543" count="9"/>
        <result id="864" enchant="10"/>
    </upgrade>

    <upgrade id="11316" item="857" enchantment="12" commission="11174400">
        <material id="1459" count="1552"/>
        <material id="91543" count="10"/>
        <result id="864" enchant="11"/>
    </upgrade>

    <upgrade id="11317" item="857" enchantment="13" commission="13036800">
        <material id="1459" count="1811"/>
        <material id="91543" count="12"/>
        <result id="864" enchant="12"/>
    </upgrade>

    <upgrade id="11318" item="857" enchantment="14" commission="14899200">
        <material id="1459" count="2070"/>
        <material id="91543" count="13"/>
        <result id="864" enchant="13"/>
    </upgrade>

    <upgrade id="11319" item="857" enchantment="15" commission="16761600">
        <material id="1459" count="2328"/>
        <material id="91543" count="15"/>
        <result id="864" enchant="14"/>
    </upgrade>

    <upgrade id="11320" item="857" enchantment="16" commission="18624000">
        <material id="1459" count="2587"/>
        <material id="91543" count="17"/>
        <result id="864" enchant="15"/>
    </upgrade>

    <upgrade id="11321" item="857" enchantment="17" commission="22348800">
        <material id="1459" count="3104"/>
        <material id="91543" count="20"/>
        <result id="864" enchant="16"/>
    </upgrade>

    <upgrade id="11322" item="857" enchantment="18" commission="26073600">
        <material id="1459" count="3622"/>
        <material id="91543" count="23"/>
        <result id="864" enchant="17"/>
    </upgrade>

    <upgrade id="11323" item="857" enchantment="19" commission="29798400">
        <material id="1459" count="4139"/>
        <material id="91543" count="27"/>
        <result id="864" enchant="18"/>
    </upgrade>

    <upgrade id="11324" item="857" enchantment="20" commission="37248000">
        <material id="1459" count="5174"/>
        <material id="91543" count="33"/>
        <result id="864" enchant="19"/>
    </upgrade>

    <upgrade id="11325" item="856" enchantment="8" commission="2376000">
        <material id="1460" count="264"/>
        <material id="91544" count="2"/>
        <result id="864" enchant="7"/>
    </upgrade>

    <upgrade id="11326" item="856" enchantment="9" commission="3564000">
        <material id="1460" count="396"/>
        <material id="91544" count="4"/>
        <result id="864" enchant="8"/>
    </upgrade>

    <upgrade id="11327" item="856" enchantment="10" commission="5940000">
        <material id="1460" count="660"/>
        <material id="91544" count="6"/>
        <result id="864" enchant="9"/>
    </upgrade>

    <upgrade id="11328" item="856" enchantment="11" commission="6534000">
        <material id="1460" count="726"/>
        <material id="91544" count="7"/>
        <result id="864" enchant="10"/>
    </upgrade>

    <upgrade id="11329" item="856" enchantment="12" commission="7128000">
        <material id="1460" count="792"/>
        <material id="91544" count="7"/>
        <result id="864" enchant="11"/>
    </upgrade>

    <upgrade id="11330" item="856" enchantment="13" commission="8316000">
        <material id="1460" count="924"/>
        <material id="91544" count="8"/>
        <result id="864" enchant="12"/>
    </upgrade>

    <upgrade id="11331" item="856" enchantment="14" commission="9504000">
        <material id="1460" count="1056"/>
        <material id="91544" count="10"/>
        <result id="864" enchant="13"/>
    </upgrade>

    <upgrade id="11332" item="856" enchantment="15" commission="10692000">
        <material id="1460" count="1188"/>
        <material id="91544" count="11"/>
        <result id="864" enchant="14"/>
    </upgrade>

    <upgrade id="11333" item="856" enchantment="16" commission="11880000">
        <material id="1460" count="1320"/>
        <material id="91544" count="12"/>
        <result id="864" enchant="15"/>
    </upgrade>

    <upgrade id="11334" item="856" enchantment="17" commission="14256000">
        <material id="1460" count="1584"/>
        <material id="91544" count="14"/>
        <result id="864" enchant="16"/>
    </upgrade>

    <upgrade id="11335" item="856" enchantment="18" commission="16632000">
        <material id="1460" count="1848"/>
        <material id="91544" count="17"/>
        <result id="864" enchant="17"/>
    </upgrade>

    <upgrade id="11336" item="856" enchantment="19" commission="19008000">
        <material id="1460" count="2112"/>
        <material id="91544" count="19"/>
        <result id="864" enchant="18"/>
    </upgrade>

    <upgrade id="11337" item="856" enchantment="20" commission="23760000">
        <material id="1460" count="2640"/>
        <material id="91544" count="24"/>
        <result id="864" enchant="19"/>
    </upgrade>

    <upgrade id="11338" item="864" enchantment="8" commission="8640000">
        <material id="1460" count="400"/>
        <material id="91545" count="5"/>
        <result id="6327" enchant="7"/>
    </upgrade>

    <upgrade id="11339" item="864" enchantment="9" commission="12960000">
        <material id="1460" count="600"/>
        <material id="91545" count="8"/>
        <result id="6327" enchant="8"/>
    </upgrade>

    <upgrade id="11340" item="864" enchantment="10" commission="21600000">
        <material id="1460" count="1000"/>
        <material id="91545" count="14"/>
        <result id="6327" enchant="9"/>
    </upgrade>

    <upgrade id="11341" item="864" enchantment="11" commission="23760000">
        <material id="1460" count="1100"/>
        <material id="91545" count="15"/>
        <result id="6327" enchant="10"/>
    </upgrade>

    <upgrade id="11342" item="864" enchantment="12" commission="25920000">
        <material id="1460" count="1200"/>
        <material id="91545" count="16"/>
        <result id="6327" enchant="11"/>
    </upgrade>

    <upgrade id="11343" item="864" enchantment="13" commission="30240000">
        <material id="1460" count="1400"/>
        <material id="91545" count="19"/>
        <result id="6327" enchant="12"/>
    </upgrade>

    <upgrade id="11344" item="864" enchantment="14" commission="34560000">
        <material id="1460" count="1600"/>
        <material id="91545" count="22"/>
        <result id="6327" enchant="13"/>
    </upgrade>

    <upgrade id="11345" item="864" enchantment="15" commission="38880000">
        <material id="1460" count="1800"/>
